//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1_MIFTA_SETYA_PRATAMA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsemNetEntities : DbContext
    {
        public EsemNetEntities()
            : base("name=EsemNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jenis> Jenis { get; set; }
        public virtual DbSet<KodePotonganHarga> KodePotonganHarga { get; set; }
        public virtual DbSet<Komputer> Komputer { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Paket> Paket { get; set; }
        public virtual DbSet<Pengguna> Pengguna { get; set; }
        public virtual DbSet<Transaksi> Transaksi { get; set; }
    }
}
